### ISSUE TITLE
Patch on the way

### ISSUE THREAD

**Issue by JonasAlfredsson** [JonasAlfredsson/bash_fail-to-wait#2]
I reported this issue to bug-bash@gnu.org, and got a response from Chet Ramey who agreed with me that this was a regression. 

> Thanks for the report. The issue is a change between bash-5.0 and bash-5.1
> to understand PID arguments with -n. The job state wasn't restored upon
> receipt of all trapped signals and interfered with subsequent calls to
> `wait -n'.
> 
> Chet

He was also extremely quick in providing a patch, which I will attach here as well. 

I have not heard anything about when this fix will be released, but I guess it will be included in the next version.

[wait-n-reset.patch.txt](https://github.com/JonasAlfredsson/bash_fail-to-wait/files/6491340/wait-n-reset.patch.txt)

**Comment by JonasAlfredsson** [comment]
I will include the content here as well:

```diff
*** ../bash-20210513/builtins/wait.def	2021-04-26 16:50:02.000000000 -0400
--- builtins/wait.def	2021-05-16 12:43:29.000000000 -0400
***************
*** 181,184 ****
--- 181,186 ----
        status = 128 + wait_signal_received;
        wait_sigint_cleanup ();
+       if (wflags & JWAIT_WAITING)
+ 	unset_waitlist ();
        WAIT_RETURN (status);
      }
```

It will go [here ](https://github.com/bminor/bash/blob/master/builtins/wait.def#L181 )in the future, and the status of it can be viewed in the [source repository](https://git.savannah.gnu.org/cgit/bash.git) (right now in devel)

**Comment by AntonFriberg** [comment]
Very cool! Nice work!

**Comment by JonasAlfredsson** [comment]
It looks like [Bash-5.1 patch 10](https://git.savannah.gnu.org/cgit/bash.git/commit/?id=910fcdc415abeb3d7d85fb46ee0d3e804a4c47a6) includes the fix for the issue. 

I did a simple test on version 5.1.16-release (instructions [here](https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/118)), and it appears to be working so I would say this is now solved.
